# # note: requires installing arduino-makefile
# #  $ pacaur -S `arduino-mk` on arch linux
# BOARDS_TXT=/usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
# ARDUINO_CORE_PATH=/usr/share/arduino/hardware/archlinux-arduino/avr/cores/arduino
# ARDUINO_VAR_PATH=/usr/share/arduino/hardware/archlinux-arduino/avr/variants
# ARDUINO_DIR=/usr/share/arduino/hardware/archlinux-arduino/avr
# ARDMK_DIR=/usr/share/arduino
# AVR_TOOLS_DIR=/usr
# MONITOR_PORT=/dev/ttyACM*

# AVRDUDE=/usr/bin/avrdude
# AVRDUDE_CONF=/etc/avrdude.conf

# ISP_PORT=/dev/ttyACM*


# BOARD_TAG=uno

# ARDUINO_LIBRARIES=Wire Servo

# CPPFLAGS = -std=gnu++0x

# include $(ARDMK_DIR)/Arduino.mk




ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
# AVR_TOOLS_DIR = /usr
# AVRDUDE_CONF = /etc/avrdude.conf
# ARDUINO_CORE_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/cores/arduino
# BOARDS_TXT = /usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
# ARDUINO_VAR_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/variants
# BOOTLOADER_PARENT = /usr/share/arduino/hardware/archlinux-arduino/avr/bootloaders


BOARD_TAG    = uno
ARDUINO_LIBS =

include /usr/share/arduino/Arduino.mk
